### ISSUE TITLE
发送中文消息乱码了

### ISSUE THREAD

**Issue by lbx-ai** [Logiase/gomirai#12]

**Comment by Logiase** [comment]
在headers中加了charset=utf8
应该不会乱码了
（之前忘记了

**Comment by lbx-ai** [comment]
应该改成
res, err := c.HttpClient.Request().
		Path(path).
		Method("POST").
		Use(body.JSON(data)).
		SetHeader("Content-Type", "application/json;charset=utf-8").
		Send()
那个body.Json里面没有设置编码

**Comment by Logiase** [comment]
已经更新了，感谢

**Comment by ssttkkl** [comment]
现在还是不行，应该先`Use(body.JSON(data))`再`SetHeader("Content-Type", "application/json; charset=UTF-8")`，不然Use的时候会自动覆盖掉原来的Header。

**Comment by Logiase** [comment]
> 现在还是不行，应该先`Use(body.JSON(data))`再`SetHeader("Content-Type", "application/json; charset=UTF-8")`，不然Use的时候会自动覆盖掉原来的Header。

谢谢提醒
（因为我这边默认编码没问题所以没做过测试，添麻烦了，thanks
