### ISSUE TITLE
发送本地图片时希望改为先uploadImage再通过imageId发送，或者提供一个uploadImage的接口

### ISSUE THREAD

**Issue by ssttkkl** [Logiase/gomirai#13]
现在的情况我在wsl运行mirai-console，在win发送图片的话，mirai-api-http那边不认我的图片的路径导致发送失败。

**Comment by ssttkkl** [comment]
我自己试着写了一个提交PL了（

**Comment by Logiase** [comment]
wsl的文件路径应该是在/mnt下（不过我也没试过了
感谢pr
