### ISSUE TITLE
回复中文的时候乱码

### ISSUE THREAD

**Issue by aundis** [Logiase/gomirai#15]
b.SendFriendMessage(e.Sender.Id, 0, message.PlainMessage("中文消息"))

实际上回复的消息是：
ä¸­ææ¶æ¯

**Comment by Logiase** [comment]
有更具体的信息嘛，比如说机器的字符编码设定，系统等
我这边测试linux和windows都是正常的

**Comment by Logiase** [comment]
![image](https://user-images.githubusercontent.com/37612226/88358092-36701d00-cda0-11ea-9ad8-c32133f37bde.png)
![image](https://user-images.githubusercontent.com/37612226/88358110-47209300-cda0-11ea-8c90-c997d2771024.png)
![image](https://user-images.githubusercontent.com/37612226/88358119-4d167400-cda0-11ea-9db5-fd750dee4ef1.png)

**Comment by aundis** [comment]
我的电脑系统是  Win10 64位

下面是我的 go.mod
module miraiTest

go 1.14

require (
	github.com/Logiase/gomirai v0.2.1-snap
	github.com/sirupsen/logrus v1.6.0
)

使用的是 mirai_windows_386

![image](https://user-images.githubusercontent.com/61673908/88370158-0fc3dd80-cdc4-11ea-9e17-e808ea33f4ad.png)
![image](https://user-images.githubusercontent.com/61673908/88370178-1e11f980-cdc4-11ea-853e-c7d1c35a0851.png)
![image](https://user-images.githubusercontent.com/61673908/88370175-194d4580-cdc4-11ea-976c-70a2764e320e.png)

我需要在其他地方设定编码吗？

**Comment by aundis** [comment]
使用的是
 https://github.com/LXY1226/miraiOK
一键启动

**Comment by aundis** [comment]
不好意思  不是 gomirai 的问题  我直接用 Postman 测试工具发送请求  得到的也是乱码
您知道我需要在哪里设定编码吗？可否告知，万分感谢！

**Comment by ghost** [comment]
> 不好意思 不是 gomirai 的问题 我直接用 Postman 测试工具发送请求 得到的也是乱码
> 您知道我需要在哪里设定编码吗？可否告知，万分感谢！

postman添加head，可以设置charset

**Comment by aundis** [comment]
![image](https://user-images.githubusercontent.com/61673908/88371933-90d0a400-cdc7-11ea-84ce-0be1a9698a9d.png)
![image](https://user-images.githubusercontent.com/61673908/88371946-99c17580-cdc7-11ea-8f82-3ac14bdb4b0d.png)
已经在 head 设定了 charset  但是 还是乱码0.0

**Comment by aundis** [comment]
![image](https://user-images.githubusercontent.com/61673908/88372097-ddb47a80-cdc7-11ea-90a3-edd2d4837c72.png)

**Comment by aundis** [comment]
找到问题了  
和问题 
https://github.com/Logiase/gomirai/issues/12
一样
