### ISSUE TITLE
如何得到进群成员的信息呢?

### ISSUE THREAD

**Issue by aundis** [Logiase/gomirai#16]
下面是我收到 MemberJoinEvent 之后打印出来的事件内容
MemberJoinEvent
{MemberJoinEvent [] {0     {0  }} 0 0 0}

都是空的，没有成员信息。

如何得到进群成员的信息呢?

**Comment by aundis** [comment]
了解了  还没完全支持

**Comment by andyhuzhill** [comment]
其实你可以看一下 mirai-http-api 的文档
然后自己修改 gomirai 源代码获取那些信息的
