### ISSUE TITLE
这个机器人怎么用啊，主页的哪个 e 什么的链接点进去了啥都看不懂，还有急速入门里面也全是英文，点了那个围棋之旅也进不去，有没有中文的文章

### ISSUE THREAD

**Issue by HoshinoTented** [Logiase/gomirai#19]
求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊求助啊

**Comment by mzdluo123** [comment]
笑死

**Comment by StageGuard** [comment]
笑死

**Comment by Mrs4s** [comment]
笑死

**Comment by capric98** [comment]
笑死

**Comment by yyuueexxiinngg** [comment]
笑死

**Comment by Logiase** [comment]
笑死

**Comment by dfaofeng** [comment]
笑死:smile:
