### ISSUE TITLE
http-api返回格式有所改动。FetchMessage会报错cannot unmarshal object into Go value of type []gomirai.InEvent

### ISSUE THREAD

**Issue by ghost** [Logiase/gomirai#3]
FetchMessage报错cannot unmarshal object into Go value of type []gomirai.InEvent

测试代码如下：
```go
var respS []gomirai.InEvent
str := `{"code":0,"errorMessage":"","data":[{"type":"FriendMessage","messageChain":[{"type":"Source","id":1111111111,"time":1586940031},{"type":"Plain","text":"哈哈哈"}],"sender":{"id":123456789,"nickname":"Batty","remark":""}}]}`
err := json.Unmarshal([]byte(str), &respS)
if err != nil {
	fmt.Println(err)
}
fmt.Printf("%#v\n", respS)
```

**Comment by capric98** [comment]
https://github.com/mamoe/mirai-api-http/commit/8a7bdd873778997ee64f7bc9113e19fbacc03a4f

看起来`Event`的内容被放进了统一状态码里的`data`部分

**Comment by ghost** [comment]
> [mamoe/mirai-api-http@8a7bdd8](https://github.com/mamoe/mirai-api-http/commit/8a7bdd873778997ee64f7bc9113e19fbacc03a4f)
> 
> 看起来`Event`的内容被放进了统一状态码里的`data`部分

是的，但我不会git，我抓紧把git学下，挺喜欢这个项目的。
